name: Build Python Wheels

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]

jobs:
  build-wheels:
    name: Build wheel on ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: win_amd64
            runner: windows-latest
          #- platform: win_arm64
          #  runner: windows-latest
          - platform: linux_x86_64
            runner: ubuntu-latest
          #- platform: linux_aarch64
          #  runner: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'   # 构建统一用 3.13
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel setuptools auditwheel
        
    - name: Install platform dependencies (Windows)
      if: contains(matrix.platform, 'win')
      run: |
        pip install pywin32>=305
        
    - name: Verify precompiled libraries
      run: |
        cd pyidh
        echo "Checking precompiled libraries for ${{ matrix.platform }}"
        ls -la pyidh/${{ matrix.platform }}/
      shell: bash
        
    - name: Build wheel
      #cd pyidh && python -m build --wheel
      run: |
        export IDH_TARGET_PLATFORM="${{ matrix.platform }}"
        python scripts/build_wheels.py ${{ matrix.platform }}
      shell: bash
        
    #- name: Repair wheel (Linux only)
    #  if: contains(matrix.platform, 'linux')
    #  run: |
    #    cd pyidh
    #    mkdir -p wheelhouse
    #    for whl in dist/*.whl; do
    #      auditwheel repair "$whl" -w wheelhouse/
    #    done
    #  shell: bash
        
    - name: List built wheels
      run: |
        echo "Built wheels:"
        ls -la pyidh/dist/ || true
        ls -la pyidh/wheelhouse/ || true
      shell: bash
        
    - name: Upload wheel artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.platform }}
        path: |
          pyidh/dist/*.whl
          pyidh/wheelhouse/*.whl
        retention-days: 30

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build-wheels]
    if: github.event_name == 'release'
    
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: wheels/
        
    - run: |
        mkdir -p dist
        find wheels/ -name "*.whl" -exec cp {} dist/ \;
        ls -la dist/
        
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: dist/
