name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/download-artifact@v4
      with:
        path: wheels/
        
    - run: |
        mkdir -p dist
        find wheels/ -name "*.whl" -exec cp {} dist/ \;
        ls -la dist/
        
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
